apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: rjb45tbrh-nodejs-gitops
  description: This is GitOps manifest for rjb45tbrh-nodejs   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-name: rjb45tbrh-nodejs
    backstage.io/kubernetes-id: rjb45tbrh-nodejs 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: rjb45tbrh-nodejs   
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:rjb45tbrh-nodejs
